/**
 * Astrology-related type definitions for Lucky Day app
 * Defines interfaces for birth details, Chinese zodiac, Four Pillars, and astrological profiles
 */

export interface BirthDetails {
  /** Birth date */
  date: Date;
  /** Birth time in HH:MM format, null if unknown */
  time: string | null;
  /** Birth location details */
  location: {
    latitude: number;
    longitude: number;
    timezone: string;
    cityName?: string;
  };
}

export interface ChineseZodiac {
  /** Chinese zodiac animal */
  animal: 'rat' | 'ox' | 'tiger' | 'rabbit' | 'dragon' | 'snake' | 
          'horse' | 'goat' | 'monkey' | 'rooster' | 'dog' | 'pig';
  /** Associated element */
  element: 'wood' | 'fire' | 'earth' | 'metal' | 'water';
  /** Birth year */
  year: number;
}

export interface PillarData {
  /** Heavenly stem */
  stem: string;
  /** Earthly branch */
  branch: string;
  /** Associated element */
  element: string;
}

export interface FourPillars {
  /** Year pillar - represents destiny */
  year: PillarData;
  /** Month pillar - represents environment */
  month: PillarData;
  /** Day pillar - represents essence */
  day: PillarData;
  /** Hour pillar - represents inner heart */
  hour: PillarData;
}

export interface PillarDescriptions {
  /** Year pillar description (Destiny) */
  year: string;
  /** Month pillar description (Environment) */
  month: string;
  /** Day pillar description (Essence) */
  day: string;
  /** Hour pillar description (Inner Heart) */
  hour: string;
}

/**
 * Complete Chinese Astrological Profile generated by LLM
 * This is the main profile structure used throughout the app
 */
export interface AstrologicalProfile {
  /** Main profile information */
  main: {
    animal: 'rat' | 'ox' | 'tiger' | 'rabbit' | 'dragon' | 'snake' | 
            'horse' | 'goat' | 'monkey' | 'rooster' | 'dog' | 'pig';
    element: 'water' | 'wood' | 'fire' | 'metal' | 'earth';
    polarity: 'yin' | 'yang';
    identity_title: string;
    identity_description: string;
    strengths: [string, string, string];
    weaknesses: [string, string, string];
  };
  /** Element and polarity distributions */
  elements: {
    element_distribution: {
      water: number;
      wood: number;
      fire: number;
      metal: number;
      earth: number;
    };
    polarity_distribution: {
      yin: number;
      yang: number;
    };
    element_polarity_description: string;
  };
  /** Ba Zi (Four Pillars) with descriptions */
  ba_zi: {
    year: {
      animal: string;
      element: string;
      polarity: string;
      description: string;
    };
    month: {
      animal: string;
      element: string;
      polarity: string;
      description: string;
    };
    day: {
      animal: string;
      element: string;
      polarity: string;
      description: string;
    };
    hour: {
      animal: string;
      element: string;
      polarity: string;
      description: string;
    };
  };
  /** Cosmic blueprint narrative */
  cosmic_blueprint: {
    full_description: string;
  };
  /** Original birth details */
  birthDetails: BirthDetails;
  /** City name for display (optional) */
  cityName?: string;
}

/**
 * Legacy profile structure for backward compatibility
 * @deprecated Use AstrologicalProfile instead
 */
export interface LegacyAstrologicalProfile {
  zodiac: ChineseZodiac;
  pillars: FourPillars;
  mysticalNickname: string;
  pillarDescriptions: PillarDescriptions;
  essenceSummary: string;
  birthDetails: BirthDetails;
  cityName?: string;
}